### ISSUE TITLE
Using model with user custom image

### ISSUE THREAD

**Issue by ramijor** [CubiCasa/CubiCasa5k#1]
Hello, I've downloaded all the data and the pretrained model and I've succesfully ran the shared notebook.

But I can't understand how to pass a new floorplan image from a custom site and get the model prediction.

**Comment by kaleaht** [comment]
You could add a code block that is something like this:
``       
fplan = cv2.imread("path to image")
fplan = cv2.cvtColor(fplan, cv2.COLOR_BGR2RGB)  # correct color channels
fplan = np.moveaxis(fplan, -1, 0) # correct the dimension oreder
fplan = 2 * (fplan / 255.0) - 1  # Normalization values to range -1 and 1
image = torch.tensor(fplan).cuda() # Convert NumPy array to Pytorch tensor
pred = model(fplan) # pass the tensor to the model
``
Then if you want to use the test time augmentation (aka. four different 90 deg rotations and then mean), you have to still rotate the tensor.

**Comment by ramijor** [comment]
Hi @kaleaht thanks for the response. If I use your code block as it is I get the following error:

`TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not numpy.ndarray`

If I change the last line to:

`pred = model(image) # pass the tensor to the model`

I end up getting the following error:

`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got input of size [3, 517, 357] instead`

**Comment by kaleaht** [comment]
Sorry forgot. The input image tensor has to have 4 dimensions -> batch, color, height, width. In this case the batch size is 1, because there is only one image. So you use unsqueeze before you pass the image to the model.
```
...
image = torch.tensor(fplan).cuda() # Convert NumPy array to Pytorch tensor
image = image.unsqueeze(0) # add extra dim 
pred = model(image) # pass the tensor to the model
```

**Comment by ramijor** [comment]
Hi @kaleaht, now I get the following error:

`RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
`

**Comment by kaleaht** [comment]
Change the image tensor to torch.cuda.FloatTensor

**Comment by shubhamwagh** [comment]
Hi!
Thanks for the code demo for model prediction on custom floorplan image.
I actually have the same question as to how to get floorplan predicted image from the model? Once you get the prediction of the model how can I view the predicted floorplan image of the same.
It is not exactly clear as the way this is to be done.
Thanks.

**Comment by ghost** [comment]
@kaleaht After the model is loaded, I use the following code to predict custom images (which works fine):
```
fplan = cv2.imread('myfloorplans/myplan.jpg')
fplan = cv2.cvtColor(fplan, cv2.COLOR_BGR2RGB)  # correct color channels
fplan = np.moveaxis(fplan, -1, 0) # correct the dimension oreder
fplan = 2 * (fplan / 255.0) - 1  # Normalization values to range -1 and 1
image = torch.FloatTensor(fplan)  # Convert NumPy array to Pytorch tensor
image = image.unsqueeze(0) # add extra dim 
pred = model(image) # pass the tensor to the model
```
Then to plot it, I try it like this:
```
pred = pred.view(pred.shape[2], pred.shape[3])
img = torch.Tensor.numpy(pred)
plt.figure(figsize=(10,10))
plt.imshow(img)
plt.show()
```
But unfortunately I get an error: 

`RuntimeError: shape '[1496, 1440]' is invalid for input of size 94786560`

I tried it with a 3rd dimension (`pred = pred.shape[1]), pred.view(pred.shape[2], pred.shape[3])`), but this doesn't work either. So my questions are:

1. How do I get the right input size? 
2. Do I have to transform the image size before predicting or plotting it?

**Comment by ghost** [comment]
@kaleaht

**Comment by kaleaht** [comment]
The output of model(image) function is a tensor and you can't plot it directly. The dimensions of this tensor are (batch size, number of all classes, height, width).

I would suggest to take a look into the samples.ipynb notebook and try to understand it. Especially what is done to the prediction tensor in section "Networks prediction for the segmentation"

**Comment by annafrosa** [comment]
Using the replies above and with samples.ipynb, I managed to do an inference of an customized image but I can only plot the images and there aren't any tutorials on how to save the images in .svg format as it is in CubiCasa5k's dataset. Can you explain better how it is done?
