### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by oschakravarthi** [CubiCasa/CubiCasa5k#10]
Hi,
I have  with 6GB memory. but still I am getting the below exception when I train.
I set the batch-size to 1 and num_workers to 0. but could not avoid this exception.
Any solution?

Thanks in advance.

RuntimeError: CUDA out of memory. Tried to allocate 646.13 MiB (GPU 0; 6.00 GiB total capacity; 3.25 GiB already allocated; 289.57 MiB free; 1.05 GiB cached)

**Comment by ccmarkus** [comment]
Your GPU probably does not have enough memory. The train set was ran with Nvidia GeForce GTX TitanX GPU with 12 gb of vram.

**Comment by raviolli** [comment]
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

should fix that. I have the same amount of RAM I run at a 16 batch size also considering stripping out some of the validation code to keep the minimum while training and use the full in the testing
