### ISSUE TITLE
Creating your own dataset

### ISSUE THREAD

**Issue by Mateo-student** [CubiCasa/CubiCasa5k#13]
Hi,

Thanks for the great contribution! I've been learning allot from this project.

This brought me to the following question: how can you create your own dataset? Or add custom data/ images?

So far I've been looking at the SVG's (in the provided dataset) and the corresponding structure of them. This makes me wonder how you have created them: did you use any specific tool or method for it?

It seems to be inaccurate and allot of work when doing this by directly manipulating the raw SVG files.

Kind regards,
Mateo

**Comment by shaunster0** [comment]
hi, I was wondering the same! Any information on how to create the required SVG's etc.

Thanks!

**Comment by ccmarkus** [comment]
Hi, 

We have been using our own in-house tool for labeling. But basically labeling your own would be pretty easy with any polygon labeling tool. I would recommend [labelme](https://github.com/wkentaro/labelme) for example
