### ISSUE TITLE
Data License

### ISSUE THREAD

**Issue by anilprasadmn** [CubiCasa/CubiCasa5k#18]
Since this work contains both a model and data, do they both follow the license mentioned?(https://github.com/CubiCasa/CubiCasa5k/blob/master/LICENSE) or are they released under terms. If so, please link that.

**Comment by ccmarkus** [comment]
Both follow the license defined in [https://github.com/CubiCasa/CubiCasa5k/blob/master/LICENSE](https://github.com/CubiCasa/CubiCasa5k/blob/master/LICENSE)
