### ISSUE TITLE
Converting Data for comparison

### ISSUE THREAD

**Issue by anilprasadmn** [CubiCasa/CubiCasa5k#19]
I am not well versed with '.svg'  data format [so apologies, if I miss anything obvious; do point it out to me] and how the ground truth is begin used. 

Is there a module in your code that can dump (or a place I can easily insert code to dump) the data in a standard CSV format?
`
csv = [   image,
              symbol, 
             polygon.positions [(px1,py1),(px2,py2)...]
         ]
` 

This will make it easy to compare the performance of other networks on this database.

**Comment by anthonymakela** [comment]
I was looking for this as well, but couldn't find anything. The following should get you started:

```python
for filename in glob.glob('cubicasa5k/colorful/*/model*'): 
    rep = open(filename.split('/')[0] + '/' + filename.split('/')[1] + '/' + filename.split('/')[2] + '/repr.txt', 'w')
    tree = ElementTree.parse(filename) 
    root = tree.getroot() 
    height = root.attrib['height'] 
    width = root.attrib['width'] 
    house = House(filename, int(float(height)), int(float(width))) 
    for i in house.representation.keys(): 
        for j in house.representation[i]: 
            xmin, ymin, xmax, ymax, label = (list(itertools.chain(*j))) 
            svg_repr = ' '.join(map(str, map(int, xmin))) + ' ' + ' '.join(map(str, map(int, ymin))) + ' ' + str(xmax) + ' ' + str(label) 
            rep.write(svg_repr + '\n') 
    rep.close() 
```

It's a bit nasty, but the loop will go through all the nested directories in `colorful` (you can use here any of the three directories containing the floor plans) and generates a text file named `repr.txt` which is the format [Raster-to-Vector ](https://github.com/art-programmer/FloorplanTransformation/) requires. Note that this is not exactly the format you were specifying, but should be pretty trivial to refactor the code. @anilprasadmn

**Comment by anilprasadmn** [comment]
Thanks a lot for that. Appreciate the help.

**Comment by sindhumallya** [comment]
I have been looking for this as well.
@anthonymakela  
house = House(filename, int(float(height)), int(float(width))) 
What does the House module do? Can you direct me to any reference for this. Thanks in advance!

**Comment by anthonymakela** [comment]
You can find the relevant file at `floortrans/loaders/house.py`. @sindhumallya
