### ISSUE TITLE
Feeding predictions to CAD for modelling

### ISSUE THREAD

**Issue by gaurav0651** [CubiCasa/CubiCasa5k#4]
Thanks for sharing this amazing work!

I want to automate 3D model generation.
How do I feed the predictions after post processing to CAD as you mentioned in fig 5 (https://arxiv.org/pdf/1904.01920.pdf)

**Comment by ccmarkus** [comment]
Hi, 

You would need to write your own converter, depending on the file type and software where you want the data to be imported.
Currently this repository does not have any CAD file exports.

The flow on figure 5 shows pipeline to CubiCasa's internal floor plan tool.

Common
