### ISSUE TITLE
Why svg file is missing part of the floorplan?

### ISSUE THREAD

**Issue by eric-yyjau** [CubiCasa/CubiCasa5k#5]
When previewing the svg file and floorplan image, we can observe that the svg file misses part of the floorplan. However, the labels extracted from the svg file seems to cover the elements correctly. Why does this happen?
Thanks!

![image](https://user-images.githubusercontent.com/17765629/60835124-3e4e2680-a177-11e9-8bcb-a9ebca173d99.png)

**Comment by ghost** [comment]
Can you post your code? Is this a custom floor plan or an internal one from Cubicasa?

**Comment by ccmarkus** [comment]
Hi, 

The svg label files are not meant to be visually viewed, they are more like information models.
Floors are on top of each other and only one floors visibility is on.
That's why the visual representation does not show all the floor side-by-side.
