### ISSUE TITLE
machine configuration 

### ISSUE THREAD

**Issue by linhanxiao** [CubiCasa/CubiCasa5k#6]
What is the machine configuration used in your  experiment, what is the configuration of the cpu, is it multi-core? How many cores?

**Comment by linhanxiao** [comment]
@kaleaht @yjuha  @ccmarkus

**Comment by kaleaht** [comment]
GPU was Nvidia GeForce GTX TitanX GPU with 12 gb of vram and i think the CPU was some intel xeon with 8 cores..

**Comment by angiereich** [comment]
Thank you for sharing the project. I am new to machine learning, so have questions regarding to machine configuration too. Is a Windows or Linux machine required? Could we run this project on something like Azure virtual machine?
